version: "2"
linters:
  default: none
  enable:
    - modernize
    - revive
    - staticcheck
formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra:
        group-params: true
    goimports:
      local-prefixes:
        - github.com/prometheus/pushgateway
